"""username unique

Revision ID: 091aa6c596aa
Revises: 38a42c2f5012
Create Date: 2018-07-18 15:55:21.273906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091aa6c596aa'
down_revision = '38a42c2f5012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_account', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='unique')
    # ### end Alembic commands ###
