"""initial setup

Revision ID: 38a42c2f5012
Revises: 
Create Date: 2018-07-18 15:01:38.452443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a42c2f5012'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('first_name', sa.String(length=128), server_default='First name', nullable=False),
    sa.Column('last_name', sa.String(length=128), server_default='Last name', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='someone@xample.org', nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('authenticated', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('ticket', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account')
    # ### end Alembic commands ###
