"""coremetadata fix

Revision ID: 475e2617a921
Revises: 091aa6c596aa
Create Date: 2018-08-09 17:14:09.012921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ARRAY, JSON
# revision identifiers, used by Alembic.
revision = '475e2617a921'
down_revision = '091aa6c596aa'
branch_labels = None
depends_on = None

class CastingArray(ARRAY):
    def bind_expression(self, bindvalue):
        return sa.cast(bindvalue, self)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('dataset_title', sa.String(length=512), nullable=False),
    sa.Column('dataset_shortname', sa.String(length=256), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('datatable', CastingArray(JSON(astext_type=sa.Text())), nullable=True),
    sa.Column('investigators', CastingArray(JSON(astext_type=sa.Text())), nullable=True),
    sa.Column('personnel', CastingArray(JSON(astext_type=sa.Text())), nullable=True),
    sa.Column('funding', CastingArray(JSON(astext_type=sa.Text())), nullable=True),
    sa.Column('methods', sa.Text(), nullable=True),
    sa.Column('geographic_location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_metadata')
    op.drop_table('status')
    # ### end Alembic commands ###
